stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python lin_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - lin_regression.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_validation:
    cmd: python linear_regression_validation.py -id data/prepared/ -im data/models/${linear_regression.model_name}.joblib -mn ${linear_regression.model_name}
    deps:
      - linear_regression_validation.py
      - data/prepared/
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_prod_version:
    cmd: python lin_regression_full.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - lin_regression_full.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression